cards = [
    # Cards do Baralho Cigano
    {"id": 1, "name": "Cavaleiro", "description": "Mensageiro, novidades chegando, movimento.", "deck_id": 1},
    {"id": 2, "name": "Trevo", "description": "Sorte rápida, pequenas oportunidades.", "deck_id": 1},
    {"id": 3, "name": "Navio", "description": "Viagem, mudanças, comércio.", "deck_id": 1},
    {"id": 4, "name": "Casa", "description": "Lar, segurança, família.", "deck_id": 1},
    {"id": 5, "name": "Árvore", "description": "Crescimento, saúde, estabilidade.", "deck_id": 1},
    {"id": 6, "name": "Nuvens", "description": "Confusão, incerteza, dúvidas.", "deck_id": 1},
    {"id": 7, "name": "Cobra", "description": "Traição, sedução, sabedoria oculta.", "deck_id": 1},
    {"id": 8, "name": "Caixão", "description": "Fim de ciclo, transformação, encerramento.", "deck_id": 1},
    {"id": 9, "name": "Buquê", "description": "Felicidade, presentes, gratidão.", "deck_id": 1},
    {"id": 10, "name": "Foice", "description": "Corte, decisões rápidas, fim repentino.", "deck_id": 1},
    {"id": 11, "name": "Chicote", "description": "Conflitos, repetições, discussões.", "deck_id": 1},
    {"id": 12, "name": "Pássaros", "description": "Comunicação, ansiedade, fofocas.", "deck_id": 1},
    {"id": 13, "name": "Criança", "description": "Início, inocência, novidade.", "deck_id": 1},
    {"id": 14, "name": "Raposa", "description": "Astúcia, alerta, falsidade.", "deck_id": 1},
    {"id": 15, "name": "Urso", "description": "Força, proteção, ciúmes.", "deck_id": 1},
    {"id": 16, "name": "Estrela", "description": "Guia, esperança, espiritualidade.", "deck_id": 1},
    {"id": 17, "name": "Cegonha", "description": "Mudanças positivas, novidades.", "deck_id": 1},
    {"id": 18, "name": "Cão", "description": "Amizade, lealdade, confiança.", "deck_id": 1},
    {"id": 19, "name": "Torre", "description": "Isolamento, autoridade, estrutura.", "deck_id": 1},
    {"id": 20, "name": "Jardim", "description": "Social, público, encontros.", "deck_id": 1},
    {"id": 21, "name": "Montanha", "description": "Obstáculo, desafio, resistência.", "deck_id": 1},
    {"id": 22, "name": "Caminhos", "description": "Escolhas, decisões, alternativas.", "deck_id": 1},
    {"id": 23, "name": "Ratos", "description": "Perdas, desgaste, preocupações.", "deck_id": 1},
    {"id": 24, "name": "Coração", "description": "Amor, emoções, afeto.", "deck_id": 1},
    {"id": 25, "name": "Aliança", "description": "Compromisso, acordos, parcerias.", "deck_id": 1},
    {"id": 26, "name": "Livro", "description": "Segredos, conhecimento, estudo.", "deck_id": 1},
    {"id": 27, "name": "Carta", "description": "Mensagens, documentos, notícias.", "deck_id": 1},
    {"id": 28, "name": "Homem", "description": "Figura masculina, consulente.", "deck_id": 1},
    {"id": 29, "name": "Mulher", "description": "Figura feminina, consulente.", "deck_id": 1},
    {"id": 30, "name": "Lírios", "description": "Paz, maturidade, sexualidade.", "deck_id": 1},
    {"id": 31, "name": "Sol", "description": "Sucesso, vitalidade, clareza.", "deck_id": 1},
    {"id": 32, "name": "Lua", "description": "Intuição, reconhecimento, emoções.", "deck_id": 1},
    {"id": 33, "name": "Chave", "description": "Soluções, respostas, caminhos abertos.", "deck_id": 1},
    {"id": 34, "name": "Peixes", "description": "Dinheiro, prosperidade, abundância.", "deck_id": 1},
    {"id": 35, "name": "Âncora", "description": "Estabilidade, trabalho, segurança.", "deck_id": 1},
    {"id": 36, "name": "Cruz", "description": "Destino, fé, provações, carma.", "deck_id": 1},

    # Cards do Tarô Rider-Waite
    {"id": 37, "name": "O Louco", "description": "Novos começos, liberdade, aventura.", "deck_id": 2},
    {"id": 38, "name": "O Mago", "description": "Habilidade, ação, poder pessoal.", "deck_id": 2},
    {"id": 39, "name": "A Sacerdotisa", "description": "Intuição, mistério, sabedoria oculta.", "deck_id": 2},
    {"id": 40, "name": "A Imperatriz", "description": "Fertilidade, beleza, abundância.", "deck_id": 2},
    {"id": 41, "name": "O Imperador", "description": "Autoridade, estrutura, estabilidade.", "deck_id": 2},
    {"id": 42, "name": "O Hierofante", "description": "Tradição, ensino, espiritualidade.", "deck_id": 2},
    {"id": 43, "name": "Os Enamorados", "description": "Amor, escolhas, dualidade.", "deck_id": 2},
    {"id": 44, "name": "O Carro", "description": "Vontade, vitória, direção.", "deck_id": 2},
    {"id": 45, "name": "A Força", "description": "Coragem, domínio interno, compaixão.", "deck_id": 2},
    {"id": 46, "name": "O Eremita", "description": "Busca interior, introspecção, sabedoria.", "deck_id": 2},
    {"id": 47, "name": "A Roda da Fortuna", "description": "Destino, sorte, ciclos da vida.", "deck_id": 2},
    {"id": 48, "name": "A Justiça", "description": "Equilíbrio, verdade, consequências.", "deck_id": 2},
    {"id": 49, "name": "O Enforcado", "description": "Rendição, nova perspectiva, pausa.", "deck_id": 2},
    {"id": 50, "name": "A Morte", "description": "Transformação, renascimento, encerramento.", "deck_id": 2},
    {"id": 51, "name": "A Temperança", "description": "Moderação, equilíbrio, harmonia.", "deck_id": 2},
    {"id": 52, "name": "O Diabo", "description": "Vícios, obsessão, aprisionamento.", "deck_id": 2},
    {"id": 53, "name": "A Torre", "description": "Ruptura, mudanças súbitas, despertar.", "deck_id": 2},
    {"id": 54, "name": "A Estrela", "description": "Esperança, cura, inspiração.", "deck_id": 2},
    {"id": 55, "name": "A Lua", "description": "Ilusão, medo, subconsciente.", "deck_id": 2},
    {"id": 56, "name": "O Sol", "description": "Alegria, clareza, vitalidade.", "deck_id": 2},
    {"id": 57, "name": "O Julgamento", "description": "Renovação, avaliação, despertar.", "deck_id": 2},
    {"id": 58, "name": "O Mundo", "description": "Conclusão, realização, integração.", "deck_id": 2},

    # Cards de Copas
    {"id": 59, "name": "Ás de Copas", "description": "Emoções, novos começos, amor.", "deck_id": 2},
    {"id": 60, "name": "2 de Copas", "description": "Parcerias, amor, harmonia.", "deck_id": 2},
    {"id": 61, "name": "3 de Copas", "description": "Celebração, amizade, união.", "deck_id": 2},
    {"id": 62, "name": "4 de Copas", "description": "Tédio, introspecção, contemplação.", "deck_id": 2},
    {"id": 63, "name": "5 de Copas", "description": "Perda, arrependimento, tristeza.", "deck_id": 2},
    {"id": 64, "name": "6 de Copas", "description": "Nostalgia, infância, memórias.", "deck_id": 2},
    {"id": 65, "name": "7 de Copas", "description": "Ilusões, escolhas, sonhos.", "deck_id": 2},
    {"id": 66, "name": "8 de Copas", "description": "Abandono, busca por algo mais profundo.", "deck_id": 2},
    {"id": 67, "name": "9 de Copas", "description": "Satisfação, realização, prazer.", "deck_id": 2},
    {"id": 68, "name": "10 de Copas", "description": "Felicidade, família, harmonia.", "deck_id": 2},
    {"id": 69, "name": "Pajem de Copas", "description": "Mensagens emocionais, criatividade.", "deck_id": 2},
    {"id": 70, "name": "Cavaleiro de Copas", "description": "Romantismo, idealismo, busca por amor.", "deck_id": 2},
    {"id": 71, "name": "Rainha de Copas", "description": "Empatia, intuição, compaixão.", "deck_id": 2},
    {"id": 72, "name": "Rei de Copas", "description": "Maturidade emocional, equilíbrio.", "deck_id": 2},

    # Cards de Ouros
    {"id": 73, "name": "Ás de Ouros", "description": "Novos começos financeiros, prosperidade.", "deck_id": 2},
    {"id": 74, "name": "2 de Ouros", "description": "Equilíbrio, adaptação, multitarefas.", "deck_id": 2},
    {"id": 75, "name": "3 de Ouros", "description": "Trabalho em equipe, colaboração, reconhecimento.", "deck_id": 2},
    {"id": 76, "name": "4 de Ouros", "description": "Segurança financeira, posse, controle.", "deck_id": 2},
    {"id": 77, "name": "5 de Ouros", "description": "Perda financeira, dificuldades, escassez.", "deck_id": 2},
    {"id": 78, "name": "6 de Ouros", "description": "Generosidade, equilíbrio financeiro.", "deck_id": 2},
    {"id": 79, "name": "7 de Ouros", "description": "Avaliação, paciência, colheita.", "deck_id": 2},
    {"id": 80, "name": "8 de Ouros", "description": "Trabalho árduo, aprendizado, aperfeiçoamento.", "deck_id": 2},
    {"id": 81, "name": "9 de Ouros", "description": "Independência, luxo, conquista.", "deck_id": 2},
    {"id": 82, "name": "10 de Ouros", "description": "Riqueza, legado, estabilidade familiar.", "deck_id": 2},
    {"id": 83, "name": "Pajem de Ouros", "description": "Início financeiro, oportunidades.", "deck_id": 2},
    {"id": 84, "name": "Cavaleiro de Ouros", "description": "Trabalho constante, compromisso, responsabilidade.", "deck_id": 2},
    {"id": 85, "name": "Rainha de Ouros", "description": "Praticidade, abundância, cuidado.", "deck_id": 2},
    {"id": 86, "name": "Rei de Ouros", "description": "Sucesso financeiro, liderança, estabilidade.", "deck_id": 2},
    
        # Cards de Espadas
    {"id": 87, "name": "Ás de Espadas", "description": "Clareza mental, novas ideias, verdade.", "deck_id": 2},
    {"id": 88, "name": "2 de Espadas", "description": "Indecisão, escolhas difíceis, equilíbrio.", "deck_id": 2},
    {"id": 89, "name": "3 de Espadas", "description": "Dor emocional, traição, separação.", "deck_id": 2},
    {"id": 90, "name": "4 de Espadas", "description": "Descanso, recuperação, pausa.", "deck_id": 2},
    {"id": 91, "name": "5 de Espadas", "description": "Conflito, perda, luta.", "deck_id": 2},
    {"id": 92, "name": "6 de Espadas", "description": "Viagem, transição, mudança para algo melhor.", "deck_id": 2},
    {"id": 93, "name": "7 de Espadas", "description": "Engano, furtividade, estratégias.", "deck_id": 2},
    {"id": 94, "name": "8 de Espadas", "description": "Limitações, sensação de aprisionamento.", "deck_id": 2},
    {"id": 95, "name": "9 de Espadas", "description": "Ansiedade, insônia, preocupação.", "deck_id": 2},
    {"id": 96, "name": "10 de Espadas", "description": "Fim de ciclo, traição, dor extrema.", "deck_id": 2},
    {"id": 97, "name": "Pajem de Espadas", "description": "Curiosidade, vigilância, comunicação.", "deck_id": 2},
    {"id": 98, "name": "Cavaleiro de Espadas", "description": "Coragem, ação rápida, mudanças súbitas.", "deck_id": 2},
    {"id": 99, "name": "Rainha de Espadas", "description": "Inteligência, discernimento, independência.", "deck_id": 2},
    {"id": 100, "name": "Rei de Espadas", "description": "Autoridade, verdade, justiça.", "deck_id": 2},

    # Cards de Paus
    {"id": 101, "name": "Ás de Paus", "description": "Novos começos, inspiração, paixão.", "deck_id": 2},
    {"id": 102, "name": "2 de Paus", "description": "Visão, planejamento, escolhas importantes.", "deck_id": 2},
    {"id": 103, "name": "3 de Paus", "description": "Expansão, crescimento, sucesso.", "deck_id": 2},
    {"id": 104, "name": "4 de Paus", "description": "Celebração, estabilidade, harmonização.", "deck_id": 2},
    {"id": 105, "name": "5 de Paus", "description": "Conflito, competição, desafios.", "deck_id": 2},
    {"id": 106, "name": "6 de Paus", "description": "Vitória, reconhecimento, sucesso público.", "deck_id": 2},
    {"id": 107, "name": "7 de Paus", "description": "Defesa, perseverança, luta.", "deck_id": 2},
    {"id": 108, "name": "8 de Paus", "description": "Ação rápida, movimento, mudanças inesperadas.", "deck_id": 2},
    {"id": 109, "name": "9 de Paus", "description": "Resiliência, perseverança, proteção.", "deck_id": 2},
    {"id": 110, "name": "10 de Paus", "description": "Sobrecarga, responsabilidade, pressão.", "deck_id": 2},
    {"id": 111, "name": "Pajem de Paus", "description": "Novos projetos, entusiasmo, curiosidade.", "deck_id": 2},
    {"id": 112, "name": "Cavaleiro de Paus", "description": "Energia, impulso, aventura.", "deck_id": 2},
    {"id": 113, "name": "Rainha de Paus", "description": "Confiança, independência, inspiração.", "deck_id": 2},
    {"id": 114, "name": "Rei de Paus", "description": "Liderança, visão, energia criativa.", "deck_id": 2}
    
]