topics = [
    { "id": 1, "name": "Amor", "description": "Relacionamentos românticos, sentimentos e conexões afetivas." },
    { "id": 2, "name": "Família", "description": "Dinâmica familiar, laços de sangue e convivência com parentes." },
    { "id": 3, "name": "Trabalho", "description": "Carreira, ambiente profissional e realizações no campo laboral." },
    { "id": 4, "name": "Finanças", "description": "Dinheiro, estabilidade econômica, investimentos e recursos." },
    { "id": 5, "name": "Saúde", "description": "Bem-estar físico, emocional e equilíbrio mental." },
    { "id": 6, "name": "Espiritualidade", "description": "Caminho espiritual, fé, propósito superior e conexão com o divino." },
    { "id": 7, "name": "Autoconhecimento", "description": "Descoberta pessoal, traços de personalidade e evolução interior." },
    { "id": 8, "name": "Imagem Pessoal", "description": "Autoestima, aparência, identidade e como o mundo te percebe." },
    { "id": 9, "name": "Projetos e Sonhos", "description": "Planos de vida, metas futuras e realizações pessoais." },
    { "id": 10, "name": "Vida Passada", "description": "Influências de outras vidas, karmas e heranças espirituais." },
    { "id": 11, "name": "Energia Atual", "description": "Leitura do momento presente, vibrações ao redor e foco do agora." },
    { "id": 12, "name": "Relacionamentos em Geral", "description": "Conexões interpessoais: amizades, colegas, vínculos diversos." },
    { "id": 13, "name": "Mudanças de Ciclo", "description": "Fins e recomeços, transições importantes e novos começos." },
    { "id": 14, "name": "Missão de Alma", "description": "Chamado interior, caminho de vida e propósito existencial." },
    { "id": 15, "name": "Cura Emocional", "description": "Feridas do passado, superações e libertação emocional." },
    { "id": 16, "name": "Tomada de Decisão", "description": "Dilemas, caminhos possíveis e ajuda para escolher com clareza." },
    { "id": 17, "name": "Vida Acadêmica", "description": "Estudos, aprendizado, desenvolvimento intelectual e formação." },
    { "id": 18, "name": "Casa e Lar", "description": "Ambiente doméstico, mudanças de residência, sensação de pertencimento." },
    { "id": 19, "name": "Sexualidade", "description": "Desejos, expressão sexual, intimidade e conexão com o corpo." },
    { "id": 20, "name": "Liberdade Pessoal", "description": "Independência, autenticidade e direito de ser quem se é." },
    { "id": 21, "name": "Animais de Estimação", "description": "Relação com pets, saúde e bem-estar dos animais." },
    { "id": 22, "name": "Viagens", "description": "Planejamento, experiências e aprendizados em viagens." },
    { "id": 23, "name": "Amizades", "description": "Laços de amizade, confiança e convivência social." },
    { "id": 24, "name": "Criatividade", "description": "Expressão artística, inspiração e projetos criativos." },
    { "id": 25, "name": "Tecnologia", "description": "Impacto da tecnologia na vida, uso de dispositivos e internet." },
    { "id": 26, "name": "Mudança de Cidade ou País", "description": "Adaptação, desafios e oportunidades em novos lugares." },
    { "id": 27, "name": "Justiça e Questões Legais", "description": "Processos judiciais, contratos e busca por justiça." },
    { "id": 28, "name": "Autoaceitação", "description": "Amor-próprio, respeito às próprias limitações e virtudes." },
    { "id": 29, "name": "Propósito de Vida", "description": "Busca de sentido, missão pessoal e realização." },
    { "id": 30, "name": "Saúde Mental", "description": "Bem-estar psicológico, emoções e equilíbrio mental." },
    { "id": 31, "name": "Rotina Diária", "description": "Desafios e oportunidades no cotidiano, organização e hábitos." },
    { "id": 32, "name": "Relacionamento com Colegas", "description": "Convívio no trabalho, estudos ou vizinhança." },
    { "id": 33, "name": "Gestão do Tempo", "description": "Como equilibrar tarefas, lazer e obrigações." },
    { "id": 34, "name": "Bem-estar no Trabalho", "description": "Ambiente, satisfação e equilíbrio entre vida pessoal e profissional." },
    { "id": 35, "name": "Deslocamentos e Trânsito", "description": "Viagens curtas, deslocamentos diários e imprevistos no caminho." },
    { "id": 36, "name": "Alimentação", "description": "Relação com a comida, escolhas alimentares e saúde nutricional." },
    { "id": 37, "name": "Lazer e Diversão", "description": "Momentos de relaxamento, hobbies e prazer no dia a dia." },
    { "id": 38, "name": "Autocuidado", "description": "Práticas diárias para cuidar do corpo, mente e emoções." },
    { "id": 39, "name": "Comunicação", "description": "Expressão, clareza e entendimento nas conversas cotidianas." },
    { "id": 40, "name": "Gestão de Conflitos", "description": "Resolução de desentendimentos e harmonia nas relações diárias." },
    { "id": 41, "name": "Relacionamento com Vizinhos", "description": "Convivência, respeito e interações com pessoas próximas." },
    { "id": 42, "name": "Igreja e Comunidade", "description": "Participação em grupos religiosos, eventos comunitários e apoio mútuo." },
    { "id": 43, "name": "Escola", "description": "Ambiente escolar, convivência com colegas e professores, experiências de aprendizado." },
    { "id": 44, "name": "Universidade", "description": "Vida acadêmica, desafios universitários, grupos de estudo e eventos estudantis." },
    { "id": 45, "name": "Liderança", "description": "Habilidades de liderança, gestão de equipes e desenvolvimento de líderes." },
    { "id": 46, "name": "Igreja", "description": "Participação em atividades religiosas, celebrações e encontros espirituais." },
    { "id": 47, "name": "Clube", "description": "Atividades recreativas, esportivas e sociais em clubes e associações." },
    { "id": 48, "name": "Academia", "description": "Prática de exercícios físicos, saúde e bem-estar em academias." },
    { "id": 49, "name": "Praça", "description": "Convívio social, lazer e eventos em espaços públicos abertos." },
    { "id": 50, "name": "Shopping", "description": "Compras, lazer e encontros em centros comerciais." },
    { "id": 51, "name": "Restaurante", "description": "Experiências gastronômicas, encontros e celebrações em restaurantes." },
    { "id": 52, "name": "Bar", "description": "Momentos de descontração, socialização e lazer em bares." },
    { "id": 53, "name": "Parque", "description": "Contato com a natureza, lazer ao ar livre e atividades em parques." }
]
